name: Deploy via git-ftp
on: push
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'bitnami'
          server: '34.65.199.1'
          private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './static/*'
          remote_path: '/web/' #make sure dir exist
          args: '-o ConnectTimeout=5'
